### ISSUE TITLE
Commit Error

### ISSUE THREAD

**Issue by vgorgen** [ucoruh/ce205-2022-2023-hw1-template#1]
![Capture](https://user-images.githubusercontent.com/92218276/194915060-5ff0101b-24c5-42ec-a2d0-b7afec432cef.PNG)

**Comment by ucoruh** [comment]
Can you try clone from git

10 Eki 2022 Pzt 19:44 tarihinde Veysel GORGEN ***@***.***>
şunu yazdı:
